/*
 * BERT Faq Classification Dashboard Backend
 *
 * This swagger describes the API signature of the backend of the dashboard.
 *
 * API version: 1.0.0
 * Contact: nicola.massarenti@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Faq struct {

	Id string `json:"id,omitempty"`

	MainQuestion string `json:"mainQuestion,omitempty"`

	Trained bool `json:"trained,omitempty"`

	Examples *FaqExamples `json:"examples,omitempty"`
}
