/*
 * BERT Faq Classification Dashboard Backend
 *
 * This swagger describes the API signature of the backend of the dashboard.
 *
 * API version: 1.0.0
 * Contact: nicola.massarenti@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FaqExamples struct {

	It []string `json:"it,omitempty"`

	En []string `json:"en,omitempty"`

	Fr []string `json:"fr,omitempty"`

	De []string `json:"de,omitempty"`

	Nl []string `json:"nl,omitempty"`
}
