/*
 * BERT Faq Classification Dashboard Backend
 *
 * This swagger describes the API signature of the backend of the dashboard.
 *
 * API version: 1.0.0
 * Contact: nicola.massarenti@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TrainingLogs struct {

	Id string `json:"id,omitempty"`

	Date string `json:"date,omitempty"`

	Active int32 `json:"active,omitempty"`

	Inactive int32 `json:"inactive,omitempty"`
}
