/*
 * BERT Faq Classification Dashboard Backend
 *
 * This swagger describes the API signature of the backend of the dashboard.
 *
 * API version: 1.0.0
 * Contact: nicola.massarenti@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/",
		Index,
	},

	Route{
		"DeleteFAQ",
		strings.ToUpper("Delete"),
		"/api/faq/{id}",
		DeleteFAQ,
	},

	Route{
		"GetFAQ",
		strings.ToUpper("Get"),
		"/api/faq/{id}",
		GetFAQ,
	},

	Route{
		"GetKB",
		strings.ToUpper("Get"),
		"/api/faq",
		GetKB,
	},

	Route{
		"PutFAQ",
		strings.ToUpper("Post"),
		"/api/faq/{id}",
		PutFAQ,
	},

	Route{
		"TrainFAQ",
		strings.ToUpper("Put"),
		"/api/faq/{id}",
		TrainFAQ,
	},

	Route{
		"Training",
		strings.ToUpper("Get"),
		"/api/training",
		Training,
	},
}
